name: fullstack-docker
services: 
    node-server:
        command:
            - npm
            - run
            - test
    go-server:
        command:
            - go
            - test
            - "-v"
            - ./... 
